require 'pry'
require 'net/http'
require 'open-uri'
require 'json'

require_relative 'cli.rb'
require_relative 'api.rb'
require_relative 'airlines.rb'
require_relative 'flights.rb'
require_relative 'airport.rb'